title: N's e-portfolio
description: MSc in Artficial Intelligence
theme: just-the-docs

url: https://github.com/no22138/eportfolio

aux_links:
  My GitHub Page: https://github.com/no22138/eportfolio

aux_links_new_tab: true

search_enabled: false
heading_anchors: false
has_toc: false

