title: N's e-portfolio for MSc in AI
description: MSc in Artficial Intelligence
theme: just-the-docs

url: https://github.com/no22138/eportfolio

aux_links:
  My GitHub Page: https://github.com/no22138/eportfolio

aux_links_new_tab: true

search_enabled: false


