title: N's E-portfolio
description: MSc in Artficial Intelligence
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Check out my [GitHub Page](https://github.com/no22138/eportfolio/)
